/* HİS Finans — Çek/Senet yaşam döngüsü */
(function(){
  'use strict';
  const labels={portfoyde:'Portföyde',bankaya_verildi:'Bankaya Verildi',tahsilatta:'Tahsilatta',tahsil_edildi:'Tahsil Edildi',iade:'İade / Karşılıksız'};
  const norm=v=>String(v??'').trim().toLocaleLowerCase('tr-TR').replace(/\s+/g,'_').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ç/g,'c');
  const statusKey=v=>norm(v),statusLabel=v=>labels[statusKey(v)]||String(v||'Portföyde');
  const statusClass=v=>{const k=statusKey(v);return k==='tahsil_edildi'?'goodPill':k==='iade'?'dangerPill':k==='bankaya_verildi'||k==='tahsilatta'?'pill':'status'};
  const bankName=id=>{const b=(S.banks||[]).find(x=>x.id===id);return b?((b.banka_adi||'')+(b.hesap_adi?' — '+b.hesap_adi:'')):'-'};
  const cashName=id=>{const c=(S.cash||[]).find(x=>x.id===id);return c?.kasa_adi||'-'};
  const cariName=id=>(S.cariler||[]).find(x=>x.id===id)?.unvan||'-';
  function summary(){const a=S.checks||[];const sum=k=>a.filter(x=>statusKey(x.portfoy_durumu)===k).reduce((n,x)=>n+Number(x.tutar||0),0);return {portfoy:sum('portfoyde'),bankada:sum('bankaya_verildi'),tahsilatta:sum('tahsilatta'),tahsil:sum('tahsil_edildi'),iade:sum('iade')};}
  function actionForm(x){const k=statusKey(x.portfoy_durumu),received=norm(x.yon)==='alinan';return `<div class="detail"><div>Cari<strong>${esc(cariName(x.cari_id))}</strong></div><div>Tutar<strong>${money(x.tutar)}</strong></div><div>Çek No<strong>${esc(x.cek_no||'-')}</strong></div><div>Mevcut Durum<strong>${esc(statusLabel(x.portfoy_durumu))}</strong></div></div><div class="form"><div class="full"><label>Yeni Durum *</label><select id="cfStatus"><option value="portfoyde" ${k==='portfoyde'?'selected':''}>Portföyde</option><option value="bankaya_verildi" ${k==='bankaya_verildi'?'selected':''}>Bankaya Verildi</option><option value="tahsil_edildi" ${k==='tahsil_edildi'?'selected':''}>Tahsil Edildi</option><option value="iade" ${k==='iade'?'selected':''}>İade / Karşılıksız</option></select></div><div><label>Banka</label><select id="cfBank"><option value="">Banka seçiniz</option>${bankOptions(x.banka_hesap_id||'')}</select></div><div><label>Kasa (opsiyonel)</label><select id="cfCash"><option value="">Kasa seçiniz</option>${cashOptions(x.kasa_id||'')}</select></div><div><label>Tahsil Tarihi</label><input id="cfDate" type="date" value="${esc(x.tahsil_tarihi||today())}"></div><div class="full muted">${received?'Alınan çek için bankaya verme aşamasında banka bakiyesi değişmez. Tahsil edildiğinde seçilen banka/kasaya gerçek para hareketi oluşturulur.':'Verilen çeklerde portföy/tahsilat durumu ayrı takip edilir.'}</div></div>`;}
  window.checkAction=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x)return toast('Çek bulunamadı.',true);modal('Çek İşlemi',actionForm(x),async()=>{const status=$('cfStatus').value,banka_hesap_id=$('cfBank').value||null,kasa_id=$('cfCash').value||null,tahsil_tarihi=$('cfDate').value||today();if((status==='bankaya_verildi'||status==='tahsil_edildi')&&!banka_hesap_id&&!kasa_id)throw Error('Bu aşamada banka veya kasa seçmelisiniz.');if(status==='tahsil_edildi'&&banka_hesap_id&&kasa_id)throw Error('Tahsilat için banka veya kasa seçeneklerinden yalnızca birini seçin.');const body={portfoy_durumu:status,banka_hesap_id:status==='portfoyde'||status==='iade'?null:banka_hesap_id,kasa_id:status==='portfoyde'||status==='iade'?null:kasa_id,tahsil_tarihi:status==='tahsil_edildi'?tahsil_tarihi:null};await api('cek_senetler?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(body)});closeModal();await load();toast(status==='tahsil_edildi'?'Çek tahsil edildi; banka/kasa hareketi oluşturuldu.':'Çek durumu güncellendi.');},'Güncelle');};
  window.editCheckFlow=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x)return toast('Çek bulunamadı.',true);modal('Çek / Senet Düzenle',`<div class="form"><div><label>Çek No</label><input id="efNo" value="${esc(x.cek_no||'')}"></div><div><label>Tutar *</label><input id="efAmount" type="number" step="0.01" min="0" value="${Number(x.tutar||0)}"></div><div><label>Vade Tarihi</label><input id="efDue" type="date" value="${esc(x.vade_tarihi||'')}"></div><div><label>Düzenleme Tarihi</label><input id="efIssue" type="date" value="${esc(x.duzenleme_tarihi||'')}"></div><div><label>Banka Adı</label><input id="efBankName" value="${esc(x.banka_adi||'')}"></div><div><label>Şube</label><input id="efBranch" value="${esc(x.sube||'')}"></div><div><label>Hesap No</label><input id="efAccount" value="${esc(x.hesap_no||'')}"></div><div><label>Keşideci</label><input id="efDrawer" value="${esc(x.kesideci||'')}"></div><div><label>Lehtar</label><input id="efBeneficiary" value="${esc(x.lehtar||'')}"></div><div class="full"><label>Açıklama</label><textarea id="efDesc">${esc(x.aciklama||'')}</textarea></div></div>`,async()=>{const tutar=Number($('efAmount').value);if(!tutar||tutar<0)throw Error('Tutar 0’dan büyük olmalıdır.');await api('cek_senetler?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({cek_no:$('efNo').value.trim(),tutar,vade_tarihi:$('efDue').value||null,duzenleme_tarihi:$('efIssue').value||null,banka_adi:$('efBankName').value.trim(),sube:$('efBranch').value.trim(),hesap_no:$('efAccount').value.trim(),kesideci:$('efDrawer').value.trim(),lehtar:$('efBeneficiary').value.trim(),aciklama:$('efDesc').value.trim()})});closeModal();await load();toast('Çek güncellendi.');},'Güncelle');};
  window.deleteCheckFlow=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x)return toast('Çek bulunamadı.',true);if(!confirm('Bu çek/senet kaydı silinsin mi?\n\n'+(x.cek_no||'-')+' — '+money(x.tutar)))return;try{await api('cek_senetler?id=eq.'+encodeURIComponent(id),{method:'DELETE'});await load();toast('Çek/senet silindi.');}catch(e){toast(e.message||'Çek silinemedi.',true)}};
  window.cekler=function(){const s=summary();$('view').innerHTML=pageHead('Çek / Senet','Çekin portföyden bankaya, oradan tahsilata kadar tüm yaşam döngüsünü takip edin.','+ Yeni Çek / Senet','newCheck()')+`<div class="metrics">${metric('Portföyde',money(s.portfoy),'elde bekleyen','orange')}${metric('Bankaya Verildi',money(s.bankada),'tahsilat bekliyor')}${metric('Tahsilatta',money(s.tahsilatta),'işlemde')}${metric('Tahsil Edildi',money(s.tahsil),'bankaya/kasaya geçti','green')}${metric('İade',money(s.iade),'karşılıksız','red')}</div>`+`<div class="panel"><div class="tableWrap"><table><thead><tr><th>Çek No</th><th>Cari</th><th>Yön</th><th>Vade</th><th class="num">Tutar</th><th>Durum</th><th>Para Yeri</th><th>İşlem</th></tr></thead><tbody>${(S.checks||[]).map(x=>{const k=statusKey(x.portfoy_durumu);const place=k==='tahsil_edildi'?(x.banka_hesap_id?bankName(x.banka_hesap_id):x.kasa_id?cashName(x.kasa_id):'-'):k==='bankaya_verildi'||k==='tahsilatta'?(x.banka_hesap_id?bankName(x.banka_hesap_id):'-'):'Portföy';return `<tr><td><b>${esc(x.cek_no||'-')}</b></td><td>${esc(cariName(x.cari_id))}</td><td>${norm(x.yon)==='alinan'?'Alınan':'Verilen'}</td><td>${dt(x.vade_tarihi)}</td><td class="num">${money(x.tutar)}</td><td><span class="${statusClass(x.portfoy_durumu)}">${esc(statusLabel(x.portfoy_durumu))}</span></td><td>${esc(place)}</td><td><div class="actions"><button class="ghost" onclick="checkAction('${x.id}')">İşlem</button><button class="ghost" onclick="editCheckFlow('${x.id}')">Düzenle</button><button class="dangerBtn" onclick="deleteCheckFlow('${x.id}')">Sil</button></div></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">Henüz çek/senet yok.</td></tr>'}</tbody></table></div></div>`;};
})();