/* V5C — çek/senet CRUD bypassını kapat + UI boot stabilizasyonu */
(function(){'use strict';const q=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));async function r(n,a){return api('rpc/'+n,{method:'POST',body:JSON.stringify(a)})}
window.newCheck=function(){if(!S.cariler.length)return toast('Önce cari oluşturun',true);modal('Yeni Çek / Senet',`<div class="form"><div><label>Cari *</label><select id="cc">${cariOptions()}</select></div><div><label>Tür</label><select id="ct"><option value="cek">Çek</option><option value="senet">Senet</option></select></div><div><label>Yön</label><select id="cy"><option value="alınan">Alınan</option><option value="verilen">Verilen</option></select></div><div><label>Durum</label><select id="cp"><option value="portfoyde">Portföyde</option><option value="bankaya_verildi">Bankaya Verildi</option></select></div><div><label>Çek/Senet No</label><input id="cn"></div><div><label>Tutar *</label><input id="cu" type="number" step="0.01" min="0"></div><div><label>Düzenleme Tarihi</label><input id="cd" type="date" value="${today()}"></div><div><label>Vade Tarihi</label><input id="cv" type="date"></div><div><label>Banka Adı</label><input id="cb"></div><div><label>Şube</label><input id="cs"></div><div><label>Hesap No</label><input id="ch"></div><div><label>Keşideci</label><input id="ck"></div><div><label>Lehtar</label><input id="cl"></div><div><label>Para Birimi</label><input id="cpb" value="TRY"></div><div class="full"><label>Açıklama</label><textarea id="ca"></textarea></div><div class="full v4-form-note">Çek/Senet ana işlem olarak kaydedilir. Durum değişimleri yaşam döngüsü kurallarına tabidir.</div></div>`,async()=>{const a=Number($('cu').value||0);if(!a)throw Error('Tutar zorunlu.');await mutate(()=>r('finans_cek_ekle',{p_cari:$('cc').value,p_tur:$('ct').value,p_yon:$('cy').value,p_durum:$('cp').value,p_cek_no:$('cn').value.trim()||null,p_tutar:a,p_duzenleme:$('cd').value||null,p_vade:$('cv').value||null,p_banka_adi:$('cb').value.trim()||null,p_sube:$('cs').value.trim()||null,p_hesap:$('ch').value.trim()||null,p_kesideci:$('ck').value.trim()||null,p_lehtar:$('cl').value.trim()||null,p_para:$('cpb').value.trim()||'TRY',p_aciklama:$('ca').value.trim()||null}),'Çek/Senet ana işlem olarak kaydedildi');closeModal()})};
window.editCheck=function(id){const x=S.checks.find(c=>c.id===id);if(!x)return;if(!x.islem_id)return toast('Çek/Senet ana işlem bağlantısı bulunamadı.',true);modal('Çek / Senet Düzenle',`<div class="form"><div><label>Cari *</label><select id="cc">${cariOptions(x.cari_id)}</select></div><div><label>Çek/Senet No</label><input id="cn" value="${q(x.cek_no||'')}"></div><div><label>Tutar *</label><input id="cu" type="number" step="0.01" value="${Number(x.tutar||0)}"></div><div><label>Düzenleme</label><input id="cd" type="date" value="${x.duzenleme_tarihi||''}"></div><div><label>Vade</label><input id="cv" type="date" value="${x.vade_tarihi||''}"></div><div class="full"><label>Açıklama</label><textarea id="ca">${q(x.aciklama||'')}</textarea></div><div class="full v4-form-note">Portföyden çıkmış çek/senet doğrudan düzenlenmez; durum işlemi üzerinden yönetilir.</div></div>`,async()=>{const a=Number($('cu').value||0);if(!a)throw Error('Tutar zorunlu.');await mutate(()=>r('finans_cek_duzenle',{p_islem:x.islem_id,p_cari:$('cc').value,p_cek_no:$('cn').value.trim()||null,p_tutar:a,p_duzenleme:$('cd').value||null,p_vade:$('cv').value||null,p_aciklama:$('ca').value.trim()||null}),'Çek/Senet ana işlem güncellendi');closeModal()})};
window.deleteCheck=async function(id){const x=S.checks.find(c=>c.id===id);if(!x?.islem_id)return toast('Çek/Senet ana işlem bağlantısı bulunamadı.',true);if(!confirm('Çek/Senet ana işlemi iptal edilsin mi?'))return;await mutate(()=>r('finans_islem_iptal',{p_islem:x.islem_id,p_neden:'Kullanıcı tarafından iptal edildi'}),'Çek/Senet iptal edildi')};

/* Tüm V5 patchleri yüklendikten sonra ekranı birkaç kez zorunlu olarak yeniden kur. */
function stabilize(){try{if(typeof window.nav==='function'&&window.S)window.nav(window.S.page||'dashboard')}catch(e){console.warn('HIS UI stabilize:',e)}}
window.__HIS_FINANS_READY=true;
setTimeout(stabilize,0);setTimeout(stabilize,150);setTimeout(stabilize,500);window.addEventListener('load',()=>setTimeout(stabilize,0),{once:true});
})();