/* HİS Finans V2 — Merkezi Banka/Kasa Transferleri
 * Sadece finans hesapları arasında para taşır; cari kullanılmaz.
 * MAIN TEST SÜRÜMÜ
 */
(function(){'use strict';
  const esc2=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money2=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(v||0));
  const date2=v=>v?new Date(v+'T00:00:00').toLocaleDateString('tr-TR'):'-';
  const api2=(p,o={})=>api(p,o);
  let showCancelled=false;
  function hesaplar(){return [...(S.banks||[]).map(x=>({id:x.id,tur:'banka',ad:`${x.banka_adi||''}${x.hesap_adi?' — '+x.hesap_adi:''}`})),...(S.cash||[]).map(x=>({id:x.id,tur:'kasa',ad:x.kasa_adi||'Kasa'}))];}
  function opts(kind,sel=''){const a=kind==='banka'?S.banks:S.cash;return (a||[]).map(x=>`<option value="${x.id}" ${String(sel)===String(x.id)?'selected':''}>${esc2(kind==='banka'?(x.banka_adi||'')+(x.hesap_adi?' — '+x.hesap_adi:''):(x.kasa_adi||''))}</option>`).join('');}
  function typeLabel(t){return t==='banka'?'Banka':'Kasa';}
  function accountName(t,id){const a=t==='banka'?S.banks:S.cash;const x=(a||[]).find(z=>z.id===id);return x?(t==='banka'?(x.banka_adi||'')+(x.hesap_adi?' — '+x.hesap_adi:''):(x.kasa_adi||'')):'-';}
  async function refreshTransfers(){try{return await api2('finans_transferler?select=*&order=tarih.desc,created_at.desc');}catch(e){toast('Transferler yüklenemedi: '+(e.message||e),true);return [];}}
  window.transferPage=async function(){
    const view=$('view');if(!view)return;
    const rows=await refreshTransfers();
    const visibleRows=showCancelled?rows:rows.filter(x=>x.durum==='aktif');
    const cancelledCount=rows.filter(x=>x.durum==='iptal').length;
    view.innerHTML=`<div class="pageHead"><div><h2>Para Transferleri</h2><p>Banka ve kasalar arasında cari kullanmadan tek işlemle para aktarın.</p></div><div class="actions"><button class="primary" onclick="newTransferV2()">+ Yeni Transfer</button></div></div><div class="metrics"><div class="metric"><small>Aktif Transfer</small><b>${rows.filter(x=>x.durum==='aktif').length}</b><span>işlem</span></div><div class="metric green"><small>Toplam Aktif Tutar</small><b>${money2(rows.filter(x=>x.durum==='aktif').reduce((n,x)=>n+Number(x.tutar||0),0))}</b><span>transfer</span></div><div class="metric orange"><small>Hesap Sayısı</small><b>${hesaplar().length}</b><span>banka + kasa</span></div></div><div class="panel"><div class="panelTop"><h3>Transfer Kayıtları</h3><label style="display:flex;align-items:center;gap:8px;font-weight:600;cursor:pointer"><input type="checkbox" ${showCancelled?'checked':''} onchange="toggleCancelledTransfers(this.checked)"> İptal edilenleri göster <span class="muted">(${cancelledCount})</span></label></div><div class="tableWrap"><table><thead><tr><th>Tarih</th><th>Kaynak</th><th>Hedef</th><th class="num">Tutar</th><th>Açıklama</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>${visibleRows.map(x=>`<tr><td>${date2(x.tarih)}</td><td><b>${esc2(typeLabel(x.kaynak_turu))}</b><br><small>${esc2(accountName(x.kaynak_turu,x.kaynak_id))}</small></td><td><b>${esc2(typeLabel(x.hedef_turu))}</b><br><small>${esc2(accountName(x.hedef_turu,x.hedef_id))}</small></td><td class="num">${money2(x.tutar)}</td><td>${esc2(x.aciklama||'-')}</td><td><span class="${x.durum==='aktif'?'goodPill':'dangerPill'}">${x.durum==='aktif'?'Aktif':'İptal'}</span></td><td>${x.durum==='aktif'?`<button class="secondaryBtn" onclick="editTransferV2('${x.id}')">Düzenle</button> <button class="dangerBtn" onclick="cancelTransferV2('${x.id}')">Sil</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Henüz aktif transfer yok.</td></tr>'}</tbody></table></div></div>`;
  };
  window.toggleCancelledTransfers=function(v){showCancelled=!!v;transferPage();};
  window.newTransferV2=function(){modal('Yeni Para Transferi',`<div class="form"><div><label>Tarih *</label><input id="tvDate" type="date" value="${today()}"></div><div><label>Tutar *</label><input id="tvAmount" type="number" min="0.01" step="0.01" placeholder="0,00"></div><div><label>Kaynak Türü *</label><select id="tvSourceType" onchange="syncTransferV2()"><option value="banka">Banka</option><option value="kasa">Kasa</option></select></div><div><label>Kaynak Hesap *</label><select id="tvSource">${opts('banka')}</select></div><div><label>Hedef Türü *</label><select id="tvTargetType" onchange="syncTransferV2()"><option value="kasa">Kasa</option><option value="banka">Banka</option></select></div><div><label>Hedef Hesap *</label><select id="tvTarget">${opts('kasa')}</select></div><div class="full"><label>Açıklama</label><input id="tvDesc" placeholder="Örn. Bankadan kasaya nakit çekimi"></div><div class="full muted">Bu işlemde <b>cari seçilmez</b>. Kaynak hesaptan çıkış, hedef hesaba giriş aynı işlem içinde oluşturulur.</div></div>`,async()=>{const st=$('tvSourceType').value,tt=$('tvTargetType').value,sid=$('tvSource').value,tid=$('tvTarget').value,amount=Number($('tvAmount').value);if(!sid||!tid)throw Error('Kaynak ve hedef hesap seçin.');if(st===tt&&sid===tid)throw Error('Kaynak ve hedef aynı olamaz.');if(!amount||amount<=0)throw Error('Geçerli bir tutar girin.');await api2('rpc/finans_transferi_olustur',{method:'POST',body:JSON.stringify({p_tarih:$('tvDate').value,p_tutar:amount,p_kaynak_turu:st,p_kaynak_id:sid,p_hedef_turu:tt,p_hedef_id:tid,p_aciklama:$('tvDesc').value.trim()||null})});closeModal();await load();await transferPage();toast('Transfer oluşturuldu.');},'Transferi Kaydet');};
  window.syncTransferV2=function(){const st=$('tvSourceType')?.value,tt=$('tvTargetType')?.value;if(!st||!tt)return;const ss=$('tvSource'),tg=$('tvTarget');if(ss)ss.innerHTML=opts(st);if(tg)tg.innerHTML=opts(tt);};
  window.editTransferV2=async function(id){
    const rows=await refreshTransfers();
    const x=rows.find(r=>String(r.id)===String(id));
    if(!x||x.durum!=='aktif'){toast('Aktif transfer bulunamadı.',true);return;}
    modal('Transferi Düzenle',`<div class="form"><div><label>Tarih *</label><input id="teDate" type="date" value="${esc2(x.tarih||today())}"></div><div><label>Tutar *</label><input id="teAmount" type="number" min="0.01" step="0.01" value="${Number(x.tutar||0)}"></div><div><label>Kaynak Türü *</label><select id="teSourceType" onchange="syncEditTransferV2()"><option value="banka" ${x.kaynak_turu==='banka'?'selected':''}>Banka</option><option value="kasa" ${x.kaynak_turu==='kasa'?'selected':''}>Kasa</option></select></div><div><label>Kaynak Hesap *</label><select id="teSource">${opts(x.kaynak_turu,x.kaynak_id)}</select></div><div><label>Hedef Türü *</label><select id="teTargetType" onchange="syncEditTransferV2()"><option value="kasa" ${x.hedef_turu==='kasa'?'selected':''}>Kasa</option><option value="banka" ${x.hedef_turu==='banka'?'selected':''}>Banka</option></select></div><div><label>Hedef Hesap *</label><select id="teTarget">${opts(x.hedef_turu,x.hedef_id)}</select></div><div class="full"><label>Açıklama</label><input id="teDesc" value="${esc2(x.aciklama||'')}"></div><div class="full muted">Düzenleme tek işlem olarak uygulanır. Eski banka/kasa hareketleri geri alınır ve yeni kaynak/hedef hareketleri birlikte oluşturulur.</div></div>`,async()=>{
      const st=$('teSourceType').value,tt=$('teTargetType').value,sid=$('teSource').value,tid=$('teTarget').value,amount=Number($('teAmount').value);
      if(!sid||!tid)throw Error('Kaynak ve hedef hesap seçin.');
      if(st===tt&&sid===tid)throw Error('Kaynak ve hedef aynı olamaz.');
      if(!amount||amount<=0)throw Error('Geçerli bir tutar girin.');
      await api2('rpc/finans_transferi_duzenle',{method:'POST',body:JSON.stringify({p_id:id,p_tarih:$('teDate').value,p_tutar:amount,p_kaynak_turu:st,p_kaynak_id:sid,p_hedef_turu:tt,p_hedef_id:tid,p_aciklama:$('teDesc').value.trim()||null})});
      closeModal();await load();await transferPage();toast('Transfer düzenlendi.');
    },'Değişiklikleri Kaydet');
  };
  window.syncEditTransferV2=function(){const st=$('teSourceType')?.value,tt=$('teTargetType')?.value;if(!st||!tt)return;const ss=$('teSource'),tg=$('teTarget');if(ss)ss.innerHTML=opts(st);if(tg)tg.innerHTML=opts(tt);};
  window.cancelTransferV2=async function(id){if(!confirm('Bu transferi iptal etmek istiyor musun? Banka/kasa hareketleri de geri alınır.'))return;try{await api2('rpc/finans_transferi_iptal_et',{method:'POST',body:JSON.stringify({p_id:id})});await load();await transferPage();toast('Transfer iptal edildi.');}catch(e){toast(e.message||'Transfer iptal edilemedi.',true);}};
  function installNav(){const side=$('side');if(!side)return false;if(side.querySelector('[data-v2-transfer]'))return true;const marker=[...side.querySelectorAll('.nav')].find(x=>x.textContent.includes('Kasa'));const b=document.createElement('button');b.className='nav';b.setAttribute('data-v2-transfer','1');b.innerHTML='<i>⇄</i><span>Para Transferleri</span>';b.onclick=()=>{location.hash='transferler';transferPage();};if(marker)marker.after(b);else side.appendChild(b);return true;}
  function boot(){if(!installNav())setTimeout(boot,100);}
  window.addEventListener('hashchange',()=>{if(location.hash==='#transferler')transferPage();setTimeout(installNav,30);});
  boot();
})();
