/* HİS Finans UI V4 — SADECE GÖRSEL/KULLANIM KATMANI
   Supabase çağrısı, veri yazma/silme/güncelleme, RPC veya şema değişikliği YOK.
*/
(function(){'use strict';
const css=`
.v4-toolbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:-2px 0 14px}.v4-search{flex:1;min-width:220px;height:44px;padding:0 14px;border:1px solid #d8e0eb;border-radius:12px;background:#fff;outline:none;font-size:14px}.v4-search:focus{border-color:#2563eb;box-shadow:0 0 0 3px #2563eb14}.v4-filter{height:44px;border:1px solid #d8e0eb;border-radius:12px;background:#fff;padding:0 12px;color:#25334b}.v4-count{font-size:12px;color:#718096;font-weight:700}.v4-source{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:11px;font-weight:800;white-space:nowrap}.v4-source.manual{background:#f1f5f9;color:#475569}.v4-source.transfer{background:#e0f2fe;color:#0369a1}.v4-source.tahsilat{background:#dcfce7;color:#15803d}.v4-source.fatura{background:#fef3c7;color:#92400e}.v4-source.cek{background:#f3e8ff;color:#7e22ce}.v4-lock{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:10px;background:#f8fafc;color:#64748b;font-size:11px;font-weight:800}.v4-actions{display:flex;gap:7px;flex-wrap:wrap}.v4-actions button{min-height:40px}.v4-form-note{grid-column:1/-1;padding:11px 13px;border-radius:11px;background:#eff6ff;color:#1e40af;font-size:12px;line-height:1.5}.v4-amount{font-variant-numeric:tabular-nums;letter-spacing:.1px}.v4-result{position:fixed;right:20px;bottom:20px;z-index:9999;max-width:430px;background:#fff;border:1px solid #dbe5ef;border-left:4px solid #059669;border-radius:14px;box-shadow:0 18px 50px #0002;padding:15px 17px;display:none}.v4-result.show{display:block;animation:v4in .2s ease}.v4-result b{display:block;margin-bottom:4px}.v4-result small{color:#64748b}.v4-result.bad{border-left-color:#dc2626}.v4-table thead th{position:sticky;top:0;background:#fff;z-index:1}.v4-table tbody tr:nth-child(even){background:#fafcff}.v4-table tbody tr:hover{background:#f1f5ff}.v4-linked{background:#f8fafc!important;color:#64748b!important;cursor:default!important}.v4-linked:hover{transform:none!important}.v4-sourcebox{margin:0 0 14px;padding:14px;border:1px solid #dbe5ef;border-radius:14px;background:linear-gradient(135deg,#f8fbff,#fff)}.v4-sourcebox .v4-sourcehead{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:9px}.v4-sourcebox strong{font-size:14px}.v4-sourcebox small{display:block;color:#718096;margin-top:3px}.v4-sourcebox button{margin-top:10px}.v4-sourceid{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:#64748b}.v4-relation{display:inline-flex;align-items:center;gap:6px;margin-top:4px}.v4-arrow{color:#94a3b8;font-weight:900}@keyframes v4in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@media(max-width:700px){.v4-toolbar{align-items:stretch}.v4-search,.v4-filter{width:100%;min-width:0}.v4-actions button{flex:1}.v4-result{left:12px;right:12px;bottom:12px;max-width:none}.tableWrap{border-radius:12px}.v4-table{min-width:680px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function sourceLabel(v){v=String(v||'manuel').toLocaleLowerCase('tr-TR');if(v.includes('transfer'))return ['↔','Para Transferi','transfer'];if(v.includes('tahsil'))return ['₺','Tahsilat','tahsilat'];if(v.includes('fatura'))return ['▧','Fatura','fatura'];if(v.includes('cek')||v.includes('senet'))return ['◈','Çek / Senet','cek'];return ['•','Manuel','manual']}
function sourceBadge(v){const [i,t,c]=sourceLabel(v);return `<span class="v4-source ${c}">${i} ${t}</span>`}
function sourceTitle(row){const [icon,label]=sourceLabel(row?.kaynak_turu);const id=row?.islem_id;return {icon,label,id}}
function sourceTarget(row){if(!row?.islem_id)return null;const k=String(row.kaynak_turu||'').toLocaleLowerCase('tr-TR');if(k.includes('tahsil')){const x=(S.payments||[]).find(p=>String(p.islem_id)===String(row.islem_id));return x?{page:'tahsilatlar',id:x.id,label:`Tahsilat ${x.belge_no||''}`.trim()}:null}if(k.includes('fatura')){const x=(S.invoices||[]).find(p=>String(p.islem_id)===String(row.islem_id));return x?{page:'faturalar',id:x.id,label:`Fatura ${x.fatura_no||''}`.trim()}:null}return null}
function openSource(row){const s=sourceTitle(row);if(!s.id){toast('Bu hareket için ana işlem bağlantısı bulunamadı.',true);return}const target=sourceTarget(row);const targetText=target?target.label:`${s.label} #${String(s.id).slice(0,8)}`;modal('Ana İşlem Bağlantısı',`<div class="v4-sourcebox"><div class="v4-sourcehead"><div>${sourceBadge(row.kaynak_turu)}<strong style="margin-left:8px">${esc(targetText)}</strong></div><span class="v4-sourceid">${esc(String(s.id))}</span></div><small>Bu hareket bağımsız bir işlem değildir. Kaynak ana işlem üzerinden yönetilmelidir.</small>${target?`<button class="primary" onclick="nav('${target.page}');setTimeout(()=>{document.querySelectorAll('button').forEach(b=>{if(b.textContent.includes('Düzenle')||b.textContent.includes('Sil')){}})},0);closeModal()">Ana İşlemi Aç</button>`:`<button class="ghost" onclick="closeModal()">Kapat</button>`}</div>`,closeModal,'Kapat')}
function sourceCell(row){if(!row?.islem_id)return `<span class="v4-source manual">• Manuel</span>`;const s=sourceTitle(row);return `<div class="v4-relation"><span class="v4-arrow">🔗</span>${sourceBadge(row.kaynak_turu)}</div><button class="ghost" style="margin-top:6px;padding:6px 9px;font-size:11px" onclick='window.hisOpenSource(${JSON.stringify(row)})'>Ana işlemi gör</button>`}
function amountInput(input){if(!input||input.dataset.v4)return;input.dataset.v4='1';input.classList.add('v4-amount');input.setAttribute('inputmode','decimal');input.setAttribute('autocomplete','off');input.addEventListener('blur',()=>{let s=input.value.trim().replace(/\s/g,'');if(!s)return;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);if(Number.isFinite(n))input.value=n.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})});input.addEventListener('focus',()=>{let s=input.value.trim();if(!s)return;const n=Number(s.replace(/\./g,'').replace(',','.'));if(Number.isFinite(n))input.value=String(n)})}
function enhanceAmounts(){document.querySelectorAll('input').forEach(i=>{const x=((i.id||'')+' '+(i.name||'')+' '+(i.placeholder||'')).toLocaleLowerCase('tr-TR');if(/tutar|miktar|fiyat|bakiye|limit/.test(x))amountInput(i)})}
function enhanceTables(){document.querySelectorAll('table').forEach(t=>{t.classList.add('v4-table');t.querySelectorAll('td').forEach(td=>{if(td.dataset.v4source)return;const raw=td.textContent.trim();if(/^(manuel|manual|transfer|para transferi|tahsilat|fatura|çek|çek\/senet|senet)$/i.test(raw)){td.dataset.v4source='1';td.innerHTML=sourceBadge(raw)}})})}
function enhanceForms(){const title=document.querySelector('#modalTitle');const body=document.querySelector('#modalBody');if(!title||!body)return;if(body.querySelector('.v4-form-note'))return;const t=String(title.textContent||'').toLocaleLowerCase('tr-TR');let text='Bilgileri kontrol edin. Kaydetme işlemi mevcut finans motorunun kurallarına göre gerçekleştirilir.';if(t.includes('transfer'))text='Bu işlem tek bir ana Para Transferidir. Banka/Kasa yansımaları birlikte yönetilir.';else if(t.includes('tahsil'))text='Tahsilat ana işlemdir. Cari ve banka/kasa etkileri birlikte hareket eder.';else if(t.includes('fatura'))text='Fatura ana işlem olarak kaydedilir; cari etkisi ayrı bir bağımsız hareket değildir.';else if(t.includes('çek')||t.includes('senet'))text='Çek/Senet durumunu yalnızca geçerli yaşam döngüsüne göre seçin.';const n=document.createElement('div');n.className='v4-form-note';n.textContent='ℹ️ '+text;body.prepend(n)}
function enhanceLinkedRows(){document.querySelectorAll('table tbody tr').forEach(tr=>{const txt=tr.textContent.toLocaleLowerCase('tr-TR');if(/bağlı|transfer|tahsilat|fatura|çek\/senet/.test(txt)&&tr.querySelector('button')){const buttons=tr.querySelectorAll('button');buttons.forEach(b=>{const bt=b.textContent.toLocaleLowerCase('tr-TR');if(bt==='sil'&&/transfer|tahsilat|fatura|bağlı/.test(txt)){b.classList.add('v4-linked');b.title='Bağlı hareket: ana işlemden yönetilir'}})}})}
function overrideDetailViews(){
 const oldBank=window.bankDetail; window.bankDetail=function(id){const b=S.banks.find(x=>x.id===id),rows=S.bankMoves.filter(x=>x.banka_hesap_id===id);modal('Banka Hareketleri',`<div class="detail"><div><small>Hesap</small><strong>${esc(b?.banka_adi||'')}</strong></div><div><small>Bakiye</small><strong>${money(bankBal(id))}</strong></div></div><div class="actions" style="margin-bottom:15px"><button class="primary" onclick="newBankMove('${id}')">+ Banka Hareketi</button></div><div class="tableWrap"><table class="v4-table"><thead><tr><th>Tarih</th><th>Belge</th><th>Açıklama</th><th>Kaynak / Ana İşlem</th><th>Tip</th><th class="num">Tutar</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dt(x.tarih)}</td><td>${esc(x.belge_no||'-')}</td><td>${esc(x.aciklama||'-')}</td><td>${sourceCell(x)}</td><td>${x.tip==='giris'?'<span class="goodPill">GİRİŞ</span>':'<span class="dangerPill">ÇIKIŞ</span>'}</td><td class="num">${money(x.tutar)}</td><td>${x.islem_id?'<span class="v4-lock">🔒 Bağlı</span>':`<button class="dangerBtn" onclick="deleteBankMove('${x.id}')">Sil</button>`}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Hareket yok.</td></tr>'}</tbody></table></div>`,closeModal,'Kapat')};
 const oldCash=window.cashDetail; window.cashDetail=function(id){const b=S.cash.find(x=>x.id===id),rows=S.cashMoves.filter(x=>x.kasa_id===id);modal('Kasa Hareketleri',`<div class="detail"><div><small>Kasa</small><strong>${esc(b?.kasa_adi||'')}</strong></div><div><small>Bakiye</small><strong>${money(cashBal(id))}</strong></div></div><div class="actions" style="margin-bottom:15px"><button class="primary" onclick="newCashMove('${id}')">+ Kasa Hareketi</button></div><div class="tableWrap"><table class="v4-table"><thead><tr><th>Tarih</th><th>Belge</th><th>Açıklama</th><th>Kaynak / Ana İşlem</th><th>Tip</th><th class="num">Tutar</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dt(x.tarih)}</td><td>${esc(x.belge_no||'-')}</td><td>${esc(x.aciklama||'-')}</td><td>${sourceCell(x)}</td><td>${x.tip==='giris'?'<span class="goodPill">GİRİŞ</span>':'<span class="dangerPill">ÇIKIŞ</span>'}</td><td class="num">${money(x.tutar)}</td><td>${x.islem_id?'<span class="v4-lock">🔒 Bağlı</span>':`<button class="dangerBtn" onclick="deleteCashMove('${x.id}')">Sil`}</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Hareket yok.</td></tr>'}</tbody></table></div>`,closeModal,'Kapat')};
 const oldCari=window.cariDetail; window.cariDetail=function(id){const c=S.cariler.find(x=>x.id===id),rows=S.cariMoves.filter(x=>x.cari_id===id);modal('Cari Detay',`<div class="detail"><div><small>Cari</small><strong>${esc(c?.unvan||'')}</strong></div><div><small>Bakiye</small><strong>${money(cariBal(id))}</strong></div></div><div class="tableWrap"><table class="v4-table"><thead><tr><th>Tarih</th><th>Açıklama</th><th>Kaynak / Ana İşlem</th><th>Yön</th><th class="num">Tutar</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${dt(x.tarih)}</td><td>${esc(x.aciklama||x.belge_no||'-')}</td><td>${sourceCell(x)}</td><td>${x.tip==='borc'?'Borç':'Alacak'}</td><td class="num">${money(x.tutar)}</td><td>${x.islem_id?'<span class="v4-lock">🔒 Bağlı</span>':''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Hareket yok.</td></tr>'}</tbody></table></div>`,closeModal,'Kapat')};
 void oldBank; void oldCash; void oldCari;
}
function install(){enhanceAmounts();enhanceTables();enhanceForms();enhanceLinkedRows();overrideDetailViews();window.hisOpenSource=openSource;const obs=new MutationObserver(()=>{enhanceAmounts();enhanceTables();enhanceForms();enhanceLinkedRows();overrideDetailViews()});obs.observe(document.body,{subtree:true,childList:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const m=document.querySelector('.modalBg.show');if(m)window.closeModal?.()}});window.hisUIV4={sourceBadge,enhanceAmounts,enhanceTables,enhanceForms};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();