/* HİS Finans V3 Bridge
   Eski UI korunur; finansal yazımlar merkezi işlem motoruna yönlendirilir. */
(function(){'use strict';
  const rpcV3=(name,args)=>api('rpc/'+name,{method:'POST',body:JSON.stringify(args)});
  const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const errorText=e=>{let s=e?.message||String(e||'İşlem başarısız');try{const j=JSON.parse(s);s=j.message||j.details||j.hint||s}catch{}return s.replace(/^ERROR:\s*/,'').replace(/^P0001:\s*/,'')};
  const fail=e=>toast(errorText(e),true);
  const ok=async(work,msg)=>{try{await work();closeModal();await load();toast(msg)}catch(e){fail(e)}};

  // ---------- MANUEL BANKA ----------
  window.newBankMove=function(bankId){modal('Yeni Banka Hareketi',`<div class="form">
    <div><label>Banka *</label><select id="bmBank">${bankOptions(bankId||'')}</select></div>
    <div><label>Tip *</label><select id="bmTip"><option value="giris">Giriş</option><option value="cikis">Çıkış</option></select></div>
    <div><label>Tarih *</label><input id="bmDate" type="date" value="${today()}"></div>
    <div><label>Tutar *</label><input id="bmAmount" type="number" step="0.01" min="0"></div>
    <div><label>Cari (opsiyonel)</label><select id="bmCari"><option value="">Cari yok</option>${cariOptions()}</select></div>
    <div><label>Belge No</label><input id="bmDoc"></div>
    <div><label>Kategori</label><input id="bmCat" value="Manuel"></div>
    <div class="full"><label>Açıklama</label><textarea id="bmDesc"></textarea></div>
    <div class="full muted">Bu kayıt bir <b>ana işlem</b> olarak oluşturulur. Banka hareketi ve varsa cari yansıması aynı transaction içinde oluşur.</div>
  </div>`,async()=>{const tutar=Number($('bmAmount').value||0);if(tutar<=0)throw Error('Tutar 0’dan büyük olmalıdır.');await rpcV3('finans_manuel_banka_ekle',{p_banka:$('bmBank').value,p_cari:$('bmCari').value||null,p_tarih:$('bmDate').value,p_tip:$('bmTip').value,p_tutar:tutar,p_belge:$('bmDoc').value.trim()||null,p_kategori:$('bmCat').value.trim()||null,p_aciklama:$('bmDesc').value.trim()||null});closeModal();await load();toast('Banka ana işlemi oluşturuldu.')},'Kaydet')};

  // ---------- MANUEL KASA ----------
  window.newCashMove=function(cashId){modal('Yeni Kasa Hareketi',`<div class="form">
    <div><label>Kasa *</label><select id="kmCash">${cashOptions(cashId||'')}</select></div>
    <div><label>Tip *</label><select id="kmTip"><option value="giris">Giriş</option><option value="cikis">Çıkış</option></select></div>
    <div><label>Tarih *</label><input id="kmDate" type="date" value="${today()}"></div>
    <div><label>Tutar *</label><input id="kmAmount" type="number" step="0.01" min="0"></div>
    <div><label>Cari (opsiyonel)</label><select id="kmCari"><option value="">Cari yok</option>${cariOptions()}</select></div>
    <div><label>Belge No</label><input id="kmDoc"></div>
    <div><label>Kategori</label><input id="kmCat" value="Manuel"></div>
    <div class="full"><label>Açıklama</label><textarea id="kmDesc"></textarea></div>
    <div class="full muted">Kasa hareketi + varsa cari yansıması tek ana işlem altında oluşturulur.</div>
  </div>`,async()=>{const tutar=Number($('kmAmount').value||0);if(tutar<=0)throw Error('Tutar 0’dan büyük olmalıdır.');await rpcV3('finans_manuel_kasa_ekle',{p_kasa:$('kmCash').value,p_cari:$('kmCari').value||null,p_tarih:$('kmDate').value,p_tip:$('kmTip').value,p_tutar:tutar,p_belge:$('kmDoc').value.trim()||null,p_kategori:$('kmCat').value.trim()||null,p_aciklama:$('kmDesc').value.trim()||null});closeModal();await load();toast('Kasa ana işlemi oluşturuldu.')},'Kaydet')};

  // ---------- MANUEL CARİ ----------
  window.newCariMove=function(cariId){modal('Yeni Cari Hareketi',`<div class="form">
    <div><label>Cari *</label><select id="cmCari">${cariOptions(cariId||'')}</select></div>
    <div><label>Yön *</label><select id="cmTip"><option value="borc">Borç</option><option value="alacak">Alacak</option></select></div>
    <div><label>Tarih *</label><input id="cmDate" type="date" value="${today()}"></div>
    <div><label>Tutar *</label><input id="cmAmount" type="number" step="0.01" min="0"></div>
    <div><label>Vade</label><input id="cmDue" type="date"></div>
    <div><label>Belge No</label><input id="cmDoc"></div>
    <div><label>Banka (opsiyonel)</label><select id="cmBank"><option value="">Yok</option>${bankOptions()}</select></div>
    <div><label>Kasa (opsiyonel)</label><select id="cmCash"><option value="">Yok</option>${cashOptions()}</select></div>
    <div class="full"><label>Açıklama</label><textarea id="cmDesc"></textarea></div>
    <div class="full muted">Banka/kasa seçilirse bunlar da aynı ana işlem altında yansır. Bağlı çocuk kayıtlar ayrı ayrı silinemez.</div>
  </div>`,async()=>{const tutar=Number($('cmAmount').value||0),bank=$('cmBank').value||null,cash=$('cmCash').value||null;if(tutar<=0)throw Error('Tutar 0’dan büyük olmalıdır.');if(bank&&cash)throw Error('Banka veya kasa seçin; ikisini birden değil.');await rpcV3('finans_cari_hareket_ekle',{p_cari:$('cmCari').value,p_tarih:$('cmDate').value,p_tip:$('cmTip').value,p_tutar:tutar,p_vade:$('cmDue').value||null,p_belge:$('cmDoc').value.trim()||null,p_aciklama:$('cmDesc').value.trim()||null,p_banka:bank,p_kasa:cash});closeModal();await load();toast('Cari ana işlemi oluşturuldu.')},'Kaydet')};

  // ---------- TAHSİLAT ----------
  window.newPayment=function(){if(!S.cariler.length)return toast('Önce cari oluşturun',true);modal('Yeni Tahsilat',`<div class="form">
    <div><label>Cari *</label><select id="pc">${cariOptions()}</select></div>
    <div><label>Fatura</label><select id="pf"><option value="">Serbest tahsilat</option>${S.invoices.filter(x=>Number(x.kalan_tutar)>0).map(x=>`<option value="${x.id}">${safe(x.fatura_no||'-')} — ${money(x.kalan_tutar)}</option>`).join('')}</select></div>
    <div><label>Tarih</label><input id="pd" type="date" value="${today()}"></div>
    <div><label>Tutar *</label><input id="pu" type="number" step="0.01" min="0"></div>
    <div><label>Yöntem</label><select id="po"><option>Bankadan</option><option>Kasadan</option></select></div>
    <div><label>Banka</label><select id="pbank"><option value="">Seçilmedi</option>${bankOptions()}</select></div>
    <div><label>Kasa</label><select id="pcash"><option value="">Seçilmedi</option>${cashOptions()}</select></div>
    <div><label>Belge No</label><input id="pb"></div>
    <div class="full"><label>Açıklama</label><textarea id="pa" placeholder="Tahsilat açıklaması"></textarea></div>
    <div class="full muted">Tahsilat = ana işlem. Cari + banka/kasa etkileri tek transaction içinde oluşturulur.</div>
  </div>`,async()=>{const tutar=Number($('pu').value||0),bank=$('pbank').value||null,cash=$('pcash').value||null;if(tutar<=0)throw Error('Tutar 0’dan büyük olmalıdır.');if((bank&&cash)||(!bank&&!cash))throw Error('Tahsilatta yalnızca bir banka veya kasa seçin.');await rpcV3('finans_tahsilat_ekle',{p_cari:$('pc').value,p_fatura:$('pf').value||null,p_tarih:$('pd').value,p_tutar:tutar,p_yontem:$('po').value,p_banka:bank,p_kasa:cash,p_belge:$('pb').value.trim()||null,p_aciklama:$('pa').value.trim()||'Tahsilat'});closeModal();await load();toast('Tahsilat ana işlemi oluşturuldu.')},'Kaydet')};
  window.deletePayment=async function(id){const x=(S.payments||[]).find(p=>p.id===id);if(!x)return;const m=x.islem_id;if(!m)return toast('Tahsilat ana işlem bağlantısı bulunamadı.',true);if(!confirm('Tahsilat iptal edilecek. Cari ve banka/kasa etkileri birlikte geri alınacak.'))return;try{await rpcV3('finans_islem_iptal',{p_islem:m,p_neden:'Tahsilat iptali'});await load();toast('Tahsilat ve bağlı etkileri birlikte iptal edildi.')}catch(e){fail(e)}};
  window.editPayment=async function(id){const x=(S.payments||[]).find(p=>p.id===id);if(!x||!x.islem_id)return toast('Tahsilat ana işlem bağlantısı bulunamadı.',true);modal('Tahsilat Düzenle',`<div class="form"><div><label>Cari</label><select id="epc">${cariOptions(x.cari_id)}</select></div><div><label>Fatura</label><select id="epf"><option value="">Serbest</option>${S.invoices.map(i=>`<option value="${i.id}" ${i.id===x.fatura_id?'selected':''}>${safe(i.fatura_no||'-')} — ${money(i.kalan_tutar)}</option>`).join('')}</select></div><div><label>Tarih</label><input id="epd" type="date" value="${x.tarih||today()}"></div><div><label>Tutar</label><input id="epu" type="number" step="0.01" value="${Number(x.tutar||0)}"></div><div><label>Banka</label><select id="epb"><option value="">Yok</option>${bankOptions(x.banka_hesap_id||'')}</select></div><div><label>Kasa</label><select id="epk"><option value="">Yok</option>${cashOptions(x.kasa_id||'')}</select></div><div><label>Belge</label><input id="epn" value="${safe(x.belge_no||'')}"></div><div class="full"><label>Açıklama</label><textarea id="epa">${safe(x.aciklama||'')}</textarea></div></div>`,async()=>{const bank=$('epb').value||null,cash=$('epk').value||null;if((bank&&cash)||(!bank&&!cash))throw Error('Yalnızca bir banka veya kasa seçin.');await rpcV3('finans_islem_duzenle',{p_islem:x.islem_id,p_data:{cari_id:$('epc').value,fatura_id:$('epf').value||null,tarih:$('epd').value,tutar:Number($('epu').value),banka_id:bank,kasa_id:cash,belge_no:$('epn').value,aciklama:$('epa').value,yontem:bank?'Bankadan':'Kasadan'}});closeModal();await load();toast('Tahsilat ana işlemi güncellendi.')},'Güncelle')};

  // ---------- FATURA ----------
  window.newInvoice=function(){if(!S.cariler.length)return toast('Önce cari oluşturun',true);modal('Yeni Fatura / Borç',`<div class="form"><div><label>Cari *</label><select id="fc">${cariOptions()}</select></div><div><label>Fatura No</label><input id="fn"></div><div><label>Tarih</label><input id="fd" type="date" value="${today()}"></div><div><label>Vade</label><input id="fv" type="date"></div><div><label>Ara Toplam</label><input id="fa" type="number" step="0.01"></div><div><label>KDV Oranı %</label><input id="fk" type="number" value="20"></div><div><label>KDV Tutarı</label><input id="fkt" type="number" step="0.01"></div><div><label>Genel Toplam *</label><input id="fg" type="number" step="0.01"></div><div><label>Peşin Banka</label><select id="fb"><option value="">Vadeli</option>${bankOptions()}</select></div><div><label>Peşin Kasa</label><select id="fs"><option value="">Vadeli</option>${cashOptions()}</select></div><div class="full"><label>Açıklama</label><textarea id="fdesc"></textarea></div><div class="full muted">Fatura = ana işlem. Peşin ödeme varsa para girişi de aynı transaction içindedir.</div></div>`,async()=>{const total=Number($('fg').value||0),bank=$('fb').value||null,cash=$('fs').value||null;if(total<=0)throw Error('Genel toplam 0’dan büyük olmalıdır.');if(bank&&cash)throw Error('Peşin ödemede banka veya kasa seçin.');await rpcV3('finans_fatura_ekle',{p_cari:$('fc').value,p_fatura_no:$('fn').value.trim()||null,p_tarih:$('fd').value,p_vade:$('fv').value||null,p_ara:Number($('fa').value||0),p_kdv_oran:Number($('fk').value||0),p_kdv:Number($('fkt').value||0),p_total:total,p_odeme:bank?'Banka':cash?'Kasa':'Vadeli',p_aciklama:$('fdesc').value.trim()||'Fatura',p_banka:bank,p_kasa:cash});closeModal();await load();toast('Fatura ana işlemi oluşturuldu.')},'Kaydet')};
  window.editInvoice=async function(id){const x=(S.invoices||[]).find(i=>i.id===id);if(!x||!x.islem_id)return toast('Fatura ana işlem bağlantısı bulunamadı.',true);modal('Fatura Ana İşlemini Düzenle',`<div class="form"><div><label>Cari</label><select id="efc">${cariOptions(x.cari_id)}</select></div><div><label>Fatura No</label><input id="efn" value="${safe(x.fatura_no||'')}"></div><div><label>Tarih</label><input id="efd" type="date" value="${x.tarih||today()}"></div><div><label>Vade</label><input id="efv" type="date" value="${x.vade_tarihi||''}"></div><div><label>Ara Toplam</label><input id="efa" type="number" value="${Number(x.ara_toplam||0)}"></div><div><label>KDV Oranı</label><input id="efk" type="number" value="${Number(x.kdv_orani||0)}"></div><div><label>KDV Tutarı</label><input id="efkt" type="number" value="${Number(x.kdv_tutari||0)}"></div><div><label>Genel Toplam</label><input id="eft" type="number" value="${Number(x.geneltoplam||0)}"></div><div class="full"><label>Açıklama</label><textarea id="efdesc">${safe(x.aciklama||'')}</textarea></div></div>`,async()=>{await rpcV3('finans_fatura_duzenle',{p_islem:x.islem_id,p_cari:$('efc').value,p_fatura_no:$('efn').value.trim()||null,p_tarih:$('efd').value,p_vade:$('efv').value||null,p_ara:Number($('efa').value||0),p_kdv_oran:Number($('efk').value||0),p_kdv:Number($('efkt').value||0),p_total:Number($('eft').value),p_odeme:x.odeme_yontemi||'Vadeli',p_aciklama:$('efdesc').value.trim()||'Fatura'});closeModal();await load();toast('Fatura ana işlemi güncellendi.')},'Güncelle')};
  window.deleteInvoice=async function(id){const x=(S.invoices||[]).find(i=>i.id===id);if(!x||!x.islem_id)return toast('Fatura ana işlem bağlantısı bulunamadı.',true);if(!confirm('Fatura iptal edilecek. Cari etkisi birlikte geri alınacak.'))return;try{await rpcV3('finans_islem_iptal',{p_islem:x.islem_id,p_neden:'Fatura iptali'});await load();toast('Fatura ve bağlı cari etkisi birlikte iptal edildi.')}catch(e){fail(e)}};

  // ---------- ÇEK/SENET ----------
  window.newCheck=function(){if(!S.cariler.length)return toast('Önce cari oluşturun',true);modal('Yeni Çek / Senet',`<div class="form"><div><label>Cari *</label><select id="cc">${cariOptions()}</select></div><div><label>Tür</label><select id="ct"><option value="cek">Çek</option><option value="senet">Senet</option></select></div><div><label>Yön</label><select id="cy"><option value="alınan">Alınan</option><option value="verilen">Verilen</option></select></div><div><label>Durum</label><select id="cs"><option value="portfoyde">Portföyde</option></select></div><div><label>Çek/Senet No</label><input id="cn"></div><div><label>Tutar *</label><input id="cu" type="number" step="0.01"></div><div><label>Düzenleme</label><input id="cd" type="date" value="${today()}"></div><div><label>Vade</label><input id="cv" type="date"></div><div><label>Banka</label><input id="cb"></div><div><label>Şube</label><input id="csb"></div><div><label>Keşideci</label><input id="ck"></div><div><label>Lehtar</label><input id="cl"></div><div class="full"><label>Açıklama</label><textarea id="cdesc"></textarea></div><div class="full muted">Yeni çek/senet Portföyde açılır. Banka bakiyesi ancak gerçek tahsil/ödeme gerçekleştiğinde etkilenir.</div></div>`,async()=>{const tutar=Number($('cu').value||0);if(tutar<=0)throw Error('Tutar 0’dan büyük olmalıdır.');await rpcV3('finans_cek_ekle',{p_cari:$('cc').value,p_tur:$('ct').value,p_yon:$('cy').value,p_durum:'portfoyde',p_cek_no:$('cn').value.trim(),p_tutar:tutar,p_duzenleme:$('cd').value,p_vade:$('cv').value||null,p_banka_adi:$('cb').value.trim(),p_sube:$('csb').value.trim(),p_hesap:'',p_kesideci:$('ck').value.trim(),p_lehtar:$('cl').value.trim(),p_para:'TRY',p_aciklama:$('cdesc').value.trim()||'Çek/Senet'});closeModal();await load();toast('Çek/Senet ana işlemi oluşturuldu.')},'Kaydet')};
  window.editCheckFlow=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x||!x.islem_id)return toast('Çek ana işlem bağlantısı bulunamadı.',true);if(x.portfoy_durumu!=='portfoyde')return toast('Portföyden çıkmış çek/senet doğrudan düzenlenemez. İlgili işlem üzerinden ilerleyin.',true);modal('Çek / Senet Düzenle',`<div class="form"><div><label>Cari</label><select id="ec">${cariOptions(x.cari_id)}</select></div><div><label>Çek No</label><input id="en" value="${safe(x.cek_no||'')}"></div><div><label>Tutar</label><input id="eu" type="number" value="${Number(x.tutar||0)}"></div><div><label>Düzenleme</label><input id="ed" type="date" value="${x.duzenleme_tarihi||today()}"></div><div><label>Vade</label><input id="ev" type="date" value="${x.vade_tarihi||''}"></div><div class="full"><label>Açıklama</label><textarea id="ea">${safe(x.aciklama||'')}</textarea></div></div>`,async()=>{await rpcV3('finans_cek_duzenle',{p_islem:x.islem_id,p_cari:$('ec').value,p_cek_no:$('en').value.trim(),p_tutar:Number($('eu').value),p_duzenleme:$('ed').value,p_vade:$('ev').value||null,p_aciklama:$('ea').value.trim()||'Çek/Senet'});closeModal();await load();toast('Çek/Senet ana işlemi güncellendi.')},'Güncelle')};
  window.deleteCheckFlow=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x||!x.islem_id)return toast('Çek ana işlem bağlantısı bulunamadı.',true);if(!confirm('Çek/Senet ana işlemi iptal edilecek. Bağlı cari etkisi birlikte geri alınacak.'))return;try{await rpcV3('finans_islem_iptal',{p_islem:x.islem_id,p_neden:'Çek/Senet iptali'});await load();toast('Çek/Senet ana işlemi iptal edildi.')}catch(e){fail(e)}};
  window.checkAction=async function(id){const x=(S.checks||[]).find(z=>z.id===id);if(!x||!x.islem_id)return toast('Çek bulunamadı.',true);const status=String(x.portfoy_durumu||'').toLowerCase();let allowed=[];if(status==='portfoyde')allowed=x.yon==='alınan'?['bankaya_verildi','iade']:['odendi','iade'];else if(status==='bankaya_verildi')allowed=['tahsil_edildi','iade'];else allowed=[];if(!allowed.length)return toast('Bu çek terminal durumda. Yeni bir ters/iade işlemi kullanın.',true);modal('Çek / Senet İşlemi',`<div class="detail"><div>Çek No<strong>${safe(x.cek_no||'-')}</strong></div><div>Mevcut Durum<strong>${safe(x.portfoy_durumu)}</strong></div><div>Tutar<strong>${money(x.tutar)}</strong></div><div>Cari<strong>${safe((S.cariler.find(c=>c.id===x.cari_id)||{}).unvan||'-')}</strong></div></div><div class="form"><div class="full"><label>Yeni Durum</label><select id="cfStatus">${allowed.map(s=>`<option value="${s}">${s==='bankaya_verildi'?'Bankaya Ver':s==='tahsil_edildi'?'Tahsil Et':s==='odendi'?'Öde':'İade'}</option>`).join('')}</select></div><div><label>Banka</label><select id="cfBank"><option value="">Yok</option>${bankOptions(x.banka_hesap_id||'')}</select></div><div><label>Kasa</label><select id="cfCash"><option value="">Yok</option>${cashOptions(x.kasa_id||'')}</select></div><div><label>Tarih</label><input id="cfDate" type="date" value="${today()}"></div><div class="full muted">Bankaya Verildi gerçek banka bakiyesini değiştirmez. Tahsil/ödeme gerçekleştiğinde seçilen banka veya kasa gerçek bakiye hareketini alır.</div></div>`,async()=>{const s=$('cfStatus').value,b=$('cfBank').value||null,k=$('cfCash').value||null;if(s==='bankaya_verildi'&&!b)throw Error('Bankaya Verildi için banka hesabı seçin.');if((s==='tahsil_edildi'||s==='odendi')&&((b&&!k)||(!b&&!k))){}else if((s==='tahsil_edildi'||s==='odendi')&&b&&k)throw Error('Banka veya kasa seçin; ikisini birden değil.');await rpcV3('finans_cek_durum_degistir',{p_islem:x.islem_id,p_yeni:s,p_banka:b,p_kasa:k,p_tarih:$('cfDate').value});closeModal();await load();toast('Çek durumu ana işlem üzerinden güncellendi.')},'Uygula')};

  // ---------- BAĞLI HAREKET KORUMASI ----------
  async function linkedMessage(type,id){try{const rows=await api(type+'?id=eq.'+encodeURIComponent(id)+'&select=islem_id');const mid=rows?.[0]?.islem_id;if(mid){const m=await api('finans_islemleri?id=eq.'+encodeURIComponent(mid)+'&select=islem_no,islem_turu,durum');const x=m?.[0];if(x)return `🔒 İşlem gerçekleştirilemedi\nBu ${type.replace('_',' ')} #${id} kaydı ${x.islem_turu} #${x.islem_no} ana işlemine bağlıdır.\nDeğişiklik için ${x.islem_turu} modülünden ilerleyin.`}}catch(_){}return '🔒 İşlem gerçekleştirilemedi\nBu kayıt doğrudan değiştirilemez. Bağlı olduğu ana işlemden ilerleyin.'}
  window.deleteBankMove=async function(id){toast(await linkedMessage('banka_hareketleri',id),true)};
  window.deleteCashMove=async function(id){toast(await linkedMessage('kasa_hareketleri',id),true)};
  window.deleteCariMove=async function(id){toast(await linkedMessage('cari_hareketleri',id),true)};
  window.editBankMove=async function(id){toast(await linkedMessage('banka_hareketleri',id),true)};
  window.editCashMove=async function(id){toast(await linkedMessage('kasa_hareketleri',id),true)};
  window.editCariMove=async function(id){toast(await linkedMessage('cari_hareketleri',id),true)};

  // ---------- TRANSFER V2 ESKİ RPC ALIASLARI ----------
  // transfer-v2.js aynı UI'ı kullanmaya devam eder; DB tarafında artık V3 motoruna yönlenir.
  window.finansV3Ready=true;
})();
